version: '3.4'

services:
  backend:
    container_name: webapi
    image: ${DOCKER_REGISTRY-}hotelapi
    build:
      context: .
      dockerfile: HotelAPI/Dockerfile
  client:
    image: client
    container_name: client
    build:
      context: ./hotelclient
      dockerfile: Dockerfile
  proxy: 
    container_name: nginx
    image: nginx:mainline     
    depends_on:
      - backend  # Ensure the backend starts before the proxy
  postgres:
    container_name: postgres
    image: postgres:alpine3.19
    restart: always
