version: '3.4'

services:
  backend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__DefaultConnection=Host=postgres;Username=admin;Password=root;Port=5432;Database=HotelDB;Include Error Detail=true;
    ports:
      - "3000:8080"
      - "3001:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on: 
      - "postgres"
  client:
    ports:
      - "3002:3000"
  proxy:
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
  postgres:
    ports:
      - "5430:5432"
    environment: 
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=HotelDB
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  